import { Repository, DataSource } from 'typeorm';
import { Trabajo, ReporteBaseAnual, Mes, ReporteMensual } from '../entities';
import { CreateTrabajoDto, UpdateTrabajoDto } from '../dto';
import { Cliente } from '../../clientes/entities';
import { CurrentUserPayload } from '../../auth/decorators/current-user.decorator';
import { User } from '../../auth/entities/user.entity';
export declare class TrabajosService {
    private trabajoRepository;
    private clienteRepository;
    private reporteBaseRepository;
    private mesRepository;
    private reporteMensualRepository;
    private readonly userRepository;
    private dataSource;
    constructor(trabajoRepository: Repository<Trabajo>, clienteRepository: Repository<Cliente>, reporteBaseRepository: Repository<ReporteBaseAnual>, mesRepository: Repository<Mes>, reporteMensualRepository: Repository<ReporteMensual>, userRepository: Repository<User>, dataSource: DataSource);
    create(createTrabajoDto: CreateTrabajoDto, currentUser: CurrentUserPayload): Promise<Trabajo>;
    findAll(currentUser: CurrentUserPayload, usuarioId?: string): Promise<Trabajo[]>;
    findOne(id: string, currentUser: CurrentUserPayload): Promise<Trabajo>;
    update(id: string, updateTrabajoDto: UpdateTrabajoDto, currentUser: CurrentUserPayload): Promise<Trabajo>;
    remove(id: string, currentUser: CurrentUserPayload): Promise<void>;
    importarReporteBase(trabajoId: string, fileBuffer: Buffer, currentUser: CurrentUserPayload): Promise<ReporteBaseAnual>;
    private getHojasIniciales;
    private crearMesesAutomaticos;
    private crearMesesAutomaticosEnTransaccion;
    private buildListadoWhere;
    private assertCanManage;
    private assertCanAccess;
    private getTrabajoOrThrow;
    private applyEquipoVisibility;
    actualizarVentasMensualesEnExcel(trabajoId: string, mes: number, ventas: number, currentUser: CurrentUserPayload): Promise<ReporteBaseAnual>;
}
